# Chapter 4: NumPy Basics: Arrays and Vectorized Computation

In [4]:
import numpy as np

In [5]:
my_arr=np.arange(1000000)
my_list=list(range(1000000))

In [6]:
%timeit my_arr2 = my_arr * 2

6.31 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
%timeit my_list2 = [x * 2 for x in my_list]

199 ms ± 103 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## 4.1: The NumPy ndarray: A Multidimensional Array Object

In [8]:
data=np.array([[1.5,-0.1,3],[0,-3,-6.5]])

In [9]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. , -6.5]])

In [11]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30., -65.]])

In [12]:
data+data

array([[  3. ,  -0.2,   6. ],
       [  0. ,  -6. , -13. ]])

In [13]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

### Creating ndarrays

In [18]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [19]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
my_arr.shape

(1000000,)

In [21]:
my_arr.ndim

1

In [22]:
arr1.shape

(5,)

In [23]:
arr1.ndim

1

In [24]:
arr2.shape

(2, 4)

In [26]:
arr2.ndim

2

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int64')

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [35]:
np.ndim(np.zeros((3,4,5)))

3

In [37]:
np.zeros((3,4,5,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
       

In [38]:
np.empty((2,3,2))

array([[[-3.10503618e+231, -3.11108592e+231],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 2.14321575e-312,  3.12301579e-033]],

       [[ 5.92956955e-038,  5.58288680e-091],
        [ 6.12959447e-062,  1.56359995e+185],
        [ 1.49457446e-154,  8.38737948e-309]]])

In [40]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [41]:
arr1=np.array([2,3,4],dtype=np.float64)

In [42]:
arr1

array([2., 3., 4.])

In [43]:
arr2=np.array([2,3,4],dtype=np.int32)

In [44]:
arr2

array([2, 3, 4], dtype=int32)

In [45]:
arr1.dtype

dtype('float64')

In [46]:
arr2.dtype

dtype('int32')

In [47]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [48]:
arr.dtype

dtype('int64')

In [49]:
float_arr=arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [50]:
float_arr.dtype

dtype('float64')

In [51]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [52]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [54]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [55]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [56]:
numeric_strings=np.array(["1.25","-9.6","42"],dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [57]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [58]:
int_array=np.arange(10)

In [59]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
calibers=np.array([.22, .270, .357, .380, .44, .50],dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [61]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

### Arithmetic with numpy

In [65]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
2*arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [67]:
2*arr*arr

array([[ 2,  8, 18],
       [32, 50, 72]])

In [68]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [69]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [70]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [71]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [72]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [73]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [74]:
arr=np.arange(10)

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr[5]

5

In [77]:
arr[5:6]

array([5])

In [78]:
arr[5:8]

array([5, 6, 7])

In [86]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
a1[1]

array([4, 5, 6])

In [84]:
a1[1,2]

6

In [89]:
a1[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [90]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr[5:8]=12

In [92]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [93]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [94]:
arr_slice[1]=12345
arr_slice

array([   12, 12345,    12])

In [95]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [96]:
arr_slice[:]=64

In [97]:
arr_slice

array([64, 64, 64])

In [98]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [100]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
arr2d[2]

array([7, 8, 9])

In [102]:
arr2d[0][2]

3

In [103]:
arr2d[0,2]

3

In [104]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [105]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
old_values=arr3d[0].copy()

In [107]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
old_values[0]

array([1, 2, 3])

In [110]:
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [111]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
arr3d[0]=old_values

In [113]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [114]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
old_values[1]=9

In [117]:
old_values

array([[1, 2, 3],
       [9, 9, 9]])

In [118]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [119]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [120]:
arr3d[1,0]

array([7, 8, 9])

In [121]:
x=arr3d[0]

In [122]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
x[0]

array([1, 2, 3])

In [124]:
x[0]=8

In [125]:
x

array([[8, 8, 8],
       [4, 5, 6]])

In [126]:
arr3d

array([[[ 8,  8,  8],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Indexing with Slices

In [127]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [128]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [129]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [132]:
arr2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [133]:
arr2da=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2da

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [142]:
arr2da[1:3,1]

array([5, 8])

In [147]:
arr2d[:2,0:1]

array([[1],
       [4]])

In [146]:
arr2d[:2,0]

array([1, 4])

In [143]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])