In [76]:
import pandas as pd
import numpy as np

# 7.1: Handling Missing Data

In [77]:
float_data=pd.Series([1.2,-3.5,np.nan,0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [78]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [79]:
string_data=pd.Series(["aardvark",np.nan,None,"avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [80]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [81]:
float_data=pd.Series([1,2,None],dtype='float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [82]:
float_data.isna

<bound method Series.isna of 0    1.0
1    2.0
2    NaN
dtype: float64>

## Filtering Out Missing Data

In [83]:
data=pd.Series([1,np.nan,3.5,np.nan,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [84]:
data.notna()
data[data.notna()]

0     True
1    False
2     True
3    False
4     True
dtype: bool

0    1.0
2    3.5
4    7.0
dtype: float64

In [85]:
data=pd.DataFrame([[1,6.5,3],[1,np.nan,np.nan],[np.nan,np.nan,np.nan],[np.nan,6.5,3]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [86]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [87]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [88]:
data[4]=np.nan
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [89]:
data.dropna(axis="columns",how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [90]:
df=pd.DataFrame(np.random.standard_normal((7,3)))
df

0         1         2
0 -0.861209  0.215030  0.636173
1  0.882944 -0.050643 -1.086953
2 -0.404260  1.034674 -0.606529
3  1.746604  0.101975 -0.673028
4 -0.736540 -1.402834 -0.206716
5  1.030054 -1.092433  0.805069
6  1.160235 -2.618919  1.338881

In [91]:
df.iloc[:4,1]=np.nan
df

0         1         2
0 -0.861209       NaN  0.636173
1  0.882944       NaN -1.086953
2 -0.404260       NaN -0.606529
3  1.746604       NaN -0.673028
4 -0.736540 -1.402834 -0.206716
5  1.030054 -1.092433  0.805069
6  1.160235 -2.618919  1.338881

In [92]:
df.iloc[:2,2]=np.nan
df

0         1         2
0 -0.861209       NaN       NaN
1  0.882944       NaN       NaN
2 -0.404260       NaN -0.606529
3  1.746604       NaN -0.673028
4 -0.736540 -1.402834 -0.206716
5  1.030054 -1.092433  0.805069
6  1.160235 -2.618919  1.338881

In [93]:
df.dropna(thresh=2)

0         1         2
2 -0.404260       NaN -0.606529
3  1.746604       NaN -0.673028
4 -0.736540 -1.402834 -0.206716
5  1.030054 -1.092433  0.805069
6  1.160235 -2.618919  1.338881

## Filling In Missing Data

In [94]:
df.fillna(0)

0         1         2
0 -0.861209  0.000000  0.000000
1  0.882944  0.000000  0.000000
2 -0.404260  0.000000 -0.606529
3  1.746604  0.000000 -0.673028
4 -0.736540 -1.402834 -0.206716
5  1.030054 -1.092433  0.805069
6  1.160235 -2.618919  1.338881

In [95]:
df.fillna({1:0.5,2:0})

0         1         2
0 -0.861209  0.500000  0.000000
1  0.882944  0.500000  0.000000
2 -0.404260  0.500000 -0.606529
3  1.746604  0.500000 -0.673028
4 -0.736540 -1.402834 -0.206716
5  1.030054 -1.092433  0.805069
6  1.160235 -2.618919  1.338881

In [96]:
df=pd.DataFrame(np.random.standard_normal((6,3)))
df.iloc[2:,1]=np.nan
df.iloc[4:,2]=np.nan
df

0        1         2
0  0.350035 -0.40871 -2.450526
1 -0.313621 -1.40590  0.543043
2 -0.560790      NaN  0.508346
3 -1.565061      NaN  1.062253
4 -0.027897      NaN       NaN
5  0.979154      NaN       NaN

In [97]:
df.fillna(method="ffill")

0        1         2
0  0.350035 -0.40871 -2.450526
1 -0.313621 -1.40590  0.543043
2 -0.560790 -1.40590  0.508346
3 -1.565061 -1.40590  1.062253
4 -0.027897 -1.40590  1.062253
5  0.979154 -1.40590  1.062253

In [98]:
df.fillna(method="ffill",limit=2)

0        1         2
0  0.350035 -0.40871 -2.450526
1 -0.313621 -1.40590  0.543043
2 -0.560790 -1.40590  0.508346
3 -1.565061 -1.40590  1.062253
4 -0.027897      NaN  1.062253
5  0.979154      NaN  1.062253

In [99]:
data=pd.Series([1,np.nan,3.5,np.nan,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

# 7.2: Data Transformation

## Removing Duplicates

In [100]:
data=pd.DataFrame({"k1":["one","two"]*3+["two"],"k2":[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [101]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [102]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [103]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [104]:
data["v1"]=range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [105]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [106]:
data.drop_duplicates(subset=["k1","k2"])

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5

In [107]:
data.drop_duplicates(subset=["k1","k2"],keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

## Transforming Data Using a Function or Mapping

In [108]:
data=pd.DataFrame({"food":["bacon","pulled pork","bacon","pastrami","corned beef","bacon","pastrami","honey ham","nova lox"],"ounces":[4,3,12,6,7.5,8,3,5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [109]:
meat_to_animal={
    "bacon":"pig",
    "pulled pork":"pig",
    "pastrami":"cow",
    "corned beef":"cow",
    "honey ham":"pig",
    "nova lox":"salmon"
}

In [110]:
data["animal"]=data["food"].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [111]:
def get_animal(x):
    return meat_to_animal[x]

In [112]:
get_animal("bacon")

'pig'

In [113]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

## Replacing Values

In [114]:
data=pd.Series([1,-999,2,-999,-1000,3])
data

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: int64

In [115]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [116]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [117]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [118]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## Renaming Axis Indexes

In [119]:
data=pd.DataFrame(np.arange(12).reshape((3,4)),index=["Ohio","Colorado","New York"],columns=["one","two","three","four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [120]:
def transform(x):
    return x[:4].upper()

In [121]:
transform("motion")

'MOTI'

In [122]:
list1=["motion","animation","cartoon"]

In [123]:
list(map(transform,list1))

['MOTI', 'ANIM', 'CART']

In [124]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [125]:
data.index=data.index.map(transform)

In [126]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [127]:
data.rename(index=str.title,columns=str.upper)
data

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [128]:
data.rename(index={"OHIO":"INDIANA"},columns={"three":"pekaboo"})

one  two  pekaboo  four
INDIANA    0    1        2     3
COLO       4    5        6     7
NEW        8    9       10    11

## Discretization and Binning

In [129]:
ages=[20,22,25,27,21,23,37,31,65,45,41,32]

In [130]:
bins=[18,25,35,60,100]
ages_categories=pd.cut(ages,bins)
ages_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [131]:
ages_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [132]:
ages_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [133]:
ages_categories.categories[0]

Interval(18, 25, closed='right')

In [134]:
pd.value_counts(ages_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [135]:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [136]:
group_names=["Youth","YoungAdult","MiddleAged","Senior"]
pd.cut(ages,bins,labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [137]:
data=np.random.uniform(size=20)
data

array([0.11217766, 0.55033325, 0.22040363, 0.32853755, 0.50818713,
       0.88186236, 0.51440917, 0.75384008, 0.63821366, 0.08589622,
       0.08904676, 0.01795864, 0.60701911, 0.21398007, 0.01745114,
       0.25821346, 0.6925722 , 0.48188645, 0.123527  , 0.55374336])

In [138]:
pd.cut(data,4,precision=2)

[(0.017, 0.23], (0.45, 0.67], (0.017, 0.23], (0.23, 0.45], (0.45, 0.67], ..., (0.23, 0.45], (0.67, 0.88], (0.45, 0.67], (0.017, 0.23], (0.45, 0.67]]
Length: 20
Categories (4, interval[float64, right]): [(0.017, 0.23] < (0.23, 0.45] < (0.45, 0.67] < (0.67, 0.88]]

In [139]:
number_categories=pd.cut(data,4,precision=2)
pd.value_counts(number_categories)

(0.017, 0.23]    8
(0.45, 0.67]     7
(0.67, 0.88]     3
(0.23, 0.45]     2
dtype: int64

In [140]:
min(data)

0.0174511356966498

In [141]:
max(data)

0.8818623552183126

In [142]:
 bin_width=(max(data)-min(data))/4#
 bin_width

0.2161028048804157

In [143]:
0.75+(max(data)-min(data))/4

0.9661028048804157

In [144]:
0.031+bin_width

0.2471028048804157

In [145]:
0.27+bin_width

0.4861028048804157

In [146]:
data=np.random.standard_normal(1000)
quartiles=pd.qcut(data,4,precision=2)
quartiles

[(-0.68, 0.028], (0.62, 3.37], (0.62, 3.37], (0.62, 3.37], (-0.68, 0.028], ..., (0.028, 0.62], (-2.94, -0.68], (0.62, 3.37], (-2.94, -0.68], (0.028, 0.62]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.94, -0.68] < (-0.68, 0.028] < (0.028, 0.62] < (0.62, 3.37]]

In [147]:
pd.value_counts(quartiles)

(-2.94, -0.68]    250
(-0.68, 0.028]    250
(0.028, 0.62]     250
(0.62, 3.37]      250
dtype: int64

In [148]:
pd.qcut(data,[0,0.1,0.5,0.9,1]).value_counts()

(-2.929, -1.234]    100
(-1.234, 0.0276]    400
(0.0276, 1.26]      400
(1.26, 3.373]       100
dtype: int64

## Detecting and Filtering Outliers

In [149]:
data=pd.DataFrame(np.random.standard_normal((1000,4)))
data

0         1         2         3
0   -0.264160 -1.223206 -0.209236 -0.054318
1    0.486475 -0.544817  0.160251  0.512572
2   -0.611327 -0.314886  0.079256 -0.288611
3    1.510473  1.902775 -0.782449  0.685825
4    0.284982 -1.237698  1.548011  1.117631
..        ...       ...       ...       ...
995  1.113574 -0.355430 -1.691095 -1.941397
996  1.248829  0.230857  0.674305 -0.777789
997 -0.497491 -0.974946  0.653856 -1.601035
998  1.099323  0.198606 -0.802937 -0.267693
999 -0.571508 -1.006566 -0.350887 -1.169976

[1000 rows x 4 columns]

In [150]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.006011     0.000838     0.033979     0.075170
std       1.026666     0.995976     0.988617     1.017194
min      -3.730278    -2.739517    -2.952740    -3.327072
25%      -0.730346    -0.659078    -0.647759    -0.581549
50%      -0.014412    -0.005992     0.046695     0.096459
75%       0.699902     0.618757     0.678245     0.776012
max       3.240396     2.887626     3.260724     3.408120

In [151]:
col=data[2]

In [152]:
col

0     -0.209236
1      0.160251
2      0.079256
3     -0.782449
4      1.548011
         ...   
995   -1.691095
996    0.674305
997    0.653856
998   -0.802937
999   -0.350887
Name: 2, Length: 1000, dtype: float64

In [171]:
data[(data.abs()>3).any(axis=1)]

0         1         2         3
137 -3.333202 -0.588300 -0.089870  0.419498
173  0.460158 -1.557542  3.009357  0.933912
265  3.240396 -0.027597 -0.167235  0.096775
306  1.036668  1.380884  1.663385  3.408120
345  3.136432 -2.324877  0.350546 -0.203062
375 -0.646311 -1.562472  3.260724  0.170065
438 -0.075730  1.376919  0.189032 -3.042691
494  1.849037 -1.118121  3.077306 -0.891474
597  1.491705  0.044074 -0.161569  3.105512
629 -2.998730 -0.475912 -0.356575 -3.327072
645 -0.365724  0.668872  3.051301  0.319905
766 -0.868126 -0.899463 -0.782818 -3.217773
806 -3.511600  0.010298 -0.597963  0.884359
857  1.637962  0.006259 -0.325034 -3.055546
873 -3.730278  0.580181 -0.264092  1.425600

In [175]:
data[data.abs()>3]=np.sign(data)*3

In [178]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.004813     0.000838     0.033581     0.075300
std       1.020465     0.995976     0.987380     1.013597
min      -3.000000    -2.739517    -2.952740    -3.000000
25%      -0.730346    -0.659078    -0.647759    -0.581549
50%      -0.014412    -0.005992     0.046695     0.096459
75%       0.699902     0.618757     0.678245     0.776012
max       3.000000     2.887626     3.000000     3.000000

### Permutation and Random Sampling

In [179]:
df=pd.DataFrame(np.arange(5*7).reshape((5,7)))

In [180]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [182]:
sampler=np.random.permutation(5)
sampler

array([3, 2, 1, 4, 0])

In [186]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [188]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [193]:
column_sampler=np.random.permutation(7)
column_sampler
df.take(column_sampler,axis="columns")

array([3, 0, 1, 6, 2, 4, 5])

3   0   1   6   2   4   5
0   3   0   1   6   2   4   5
1  10   7   8  13   9  11  12
2  17  14  15  20  16  18  19
3  24  21  22  27  23  25  26
4  31  28  29  34  30  32  33

In [194]:
df.sample(n=3)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34

In [197]:
df.sample(n=3,replace=True)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
4  28  29  30  31  32  33  34

In [198]:
choices=pd.Series([5,7,-1,6,4])
choices.sample(n=10,replace=True)

2   -1
4    4
3    6
0    5
4    4
3    6
3    6
1    7
0    5
2   -1
dtype: int64

### Computing Indicator/Dummy Variables