# Chapter 5: Getting Started with pandas

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## 5.1: Introduction to pandas Data Structures

### Series

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.array

<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
pd.Series([1,'no',2])

0     1
1    no
2     2
dtype: object

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2["a"]

-5

In [8]:
obj3=obj2

In [9]:
obj3

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj3["a"]

-5

In [11]:
obj3["a"]="hello"

In [12]:
obj3

d        4
b        7
a    hello
c        3
dtype: object

In [13]:
obj2

d        4
b        7
a    hello
c        3
dtype: object

In [14]:
obj2[["c","b","d"]]

c    3
b    7
d    4
dtype: object

In [15]:
obj2[obj2>0]

TypeError: '>' not supported between instances of 'str' and 'int'

In [16]:
obj2["a"]=-8

In [17]:
obj2

d     4
b     7
a    -8
c     3
dtype: object

In [18]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: object

In [19]:
obj2*2

d      8
b     14
a    -16
c      6
dtype: object

In [26]:
np.exp(obj2)

TypeError: loop of ufunc does not support argument 0 of type int which has no callable exp method

In [28]:
obj2

d     4
b     7
a    -8
c     3
dtype: object

In [29]:
np.exp(obj2)

TypeError: loop of ufunc does not support argument 0 of type int which has no callable exp method

In [20]:
obj2=obj2.astype(int)

In [21]:
obj2

d    4
b    7
a   -8
c    3
dtype: int64

In [22]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.000335
c      20.085537
dtype: float64

In [23]:
"b" in obj2

True

In [24]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}


In [25]:
obj3=pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [42]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [27]:
states=['California','Ohio','Oregon','Texas']
obj4=pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [30]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [32]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [33]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [36]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [37]:
obj4.name="population"
obj4.index.name="state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [38]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [40]:
obj.index=['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [45]:
data={"state":["Ohio","Ohio","Ohio","Nevada","Nevada","Nevada"],
"year":[2000,2001,2002,2001,2002,2003],
"pop":[1.5,1.7,3.6,2.4,2.9,3.2]
}

In [46]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [47]:
frame=pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [48]:
frame.head(n=2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [49]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [50]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [51]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'])
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [53]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [54]:
frame2['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [55]:
frame2.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [57]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [58]:
frame2.iloc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [59]:
frame2['debt']=16.5
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [64]:
frame2['debt']=np.arange(6.)
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [65]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [68]:
frame2['debt']

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
Name: debt, dtype: float64

In [69]:
frame2['debt']=val
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [72]:
val2=pd.Series([-1.2, -1.5, -1.7,-1.2,-1.5,-1.7],index=["one","two","three","four","five","six"])
val2

one     -1.2
two     -1.5
three   -1.7
four    -1.2
five    -1.5
six     -1.7
dtype: float64

In [74]:
val3 = pd.Series([-1.2, -1.5, -1.7, -1.2, -1.5, -1.7],
                 index=[0, 1, "three", "four", "five", "six"])
val3


0       -1.2
1       -1.5
three   -1.7
four    -1.2
five    -1.5
six     -1.7
dtype: float64

In [73]:
frame2['debt']=val2
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [75]:
frame2['debt']=val3
frame2

year   state  pop  debt
0  2000    Ohio  1.5  -1.2
1  2001    Ohio  1.7  -1.5
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [76]:
frame2['eastern']=frame2['state']=="Ohio"
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5  -1.2     True
1  2001    Ohio  1.7  -1.5     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [77]:
del frame2['eastern']
frame2

year   state  pop  debt
0  2000    Ohio  1.5  -1.2
1  2001    Ohio  1.7  -1.5
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [78]:
populations={"Ohio":{2000:1.5,2001:1.7,2002:3.6},
"Nevada":{2001:2.4,2002:2.9,2003:3.2}}

In [79]:
populations

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6},
 'Nevada': {2001: 2.4, 2002: 2.9, 2003: 3.2}}

In [80]:
frame3=pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     3.2

In [81]:
frame3.T

2000  2001  2002  2003
Ohio     1.5   1.7   3.6   NaN
Nevada   NaN   2.4   2.9   3.2

In [82]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     3.2

In [86]:
frame3.dtypes

Ohio      float64
Nevada    float64
dtype: object

In [85]:
frame3.T.T.dtypes

Ohio      float64
Nevada    float64
dtype: object

In [87]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     3.2

In [88]:
pd.DataFrame(populations,index=[2001,2002,2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     3.2

In [89]:
frame3["Ohio"][:-1]

2000    1.5
2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [90]:
frame3["Nevada"][:2]

2000    NaN
2001    2.4
Name: Nevada, dtype: float64

In [91]:
pdata = pd.DataFrame({'Ohio': frame3["Ohio"][:-1],
'Nevada':frame3["Nevada"][:2]})
pdata


Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     NaN

In [92]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     3.2

In [93]:
frame3.index.name="year"
frame3

Ohio  Nevada
year              
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     3.2

In [94]:
frame3.columns.name="state"

In [95]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9
2003    NaN     3.2

In [101]:
frame3['Ohio']

year
2000    1.5
2001    1.7
2002    3.6
2003    NaN
Name: Ohio, dtype: float64

In [102]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5  -1.2
1  2001    Ohio  1.7  -1.5
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [110]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9],
       [nan, 3.2]])

In [113]:
frame3.shape

(4, 2)

In [120]:
x=frame3.to_numpy
x

<bound method DataFrame.to_numpy of state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9
2003    NaN     3.2>

In [124]:
x=np.array(x)

In [128]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, -1.2],
       [2001, 'Ohio', 1.7, -1.5],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [132]:
y=frame2.values
y

array([[2000, 'Ohio', 1.5, -1.2],
       [2001, 'Ohio', 1.7, -1.5],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [134]:
y[:,1]

array(['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], dtype=object)

### Index Objects

## 5.2: Essential Functionality

### Reindexing

### Dropping Entries from an Axis

### Indexing, Selection, and Filtering

### Arithmetic and Data Alignment

### Function Application and Mapping

### Sorting and Ranking

### Axis Indexes with Duplicate Labels

## 5.3: Summarizing and Computing Descriptive Statistics

### Correlation and Covariance

### Unique Values, Value Counts, and Membership